=== nmsa/tma-framework-m/development/server/python-api/apirest/schemas/atmosphere_tma-m_schema.json
{
    "title": "tma-m_schema_0_3",

    "$id": "http://atmosphere-eubrazil.eu/tma-m_schema_v0.2.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "probeId": {
            "$id": "/properties/probeId",
            "type": "integer",
            "default": -1,
            "minimum": 0
        },
        "resourceId": {
            "$id": "/properties/resourceId",
            "type": "integer",
            "default": -1,
            "minimum": 0
        },
        "messageId": {
            "$id": "/properties/messageId",
            "type": "integer",
            "default": -1,
            "minimum": 0
        },
        "sentTime": {
            "$id": "/properties/sentTime",
            "type": "integer",
            "default": -1,
            "minimum": 0
        },
        "data": {
            "$id": "/properties/data",
            "type": "array",
            "minItems": 0,
            "items": {
                "$id": "/properties/data/items",
                "type": "object",
                "properties": {
                    "type": {
                        "$id": "/properties/data/items/properties/type",
                        "type": "string",
                        "default": "measurement",
                        "enum": [
                            "measurement",
                            "event"
                        ]
                    },
                    "descriptionId": {
                        "$id": "/properties/data/items/properties/descriptionId",
                        "type": "integer",
                        "default": -10,
                        "minimum": 0
                    },
                    "observations": {
                        "$id": "/properties/data/items/properties/observations",
                        "type": "array",
                        "items": {
                            "$id": "/properties/data/items/properties/observations/items",
                            "type": "object",
                            "properties": {
                                "time": {
                                    "$id": "/properties/data/items/properties/observations/items/properties/time",
                                    "type": "integer",
                                    "default": -1,
                                    "minimum": 0
                                },
                                "value": {
                                    "$id": "/properties/data/items/properties/observations/items/properties/value",
                                    "type": "number",
                                    "default": 0
                                }
                            },
                            "required": [
                                "time"
                            ]
                        }
                    }
                },
                "required": [
                    "type",
                    "descriptionId",
                    "observations"
                ]
            }
        }
    },
    "required": [
        "probeId",
        "resourceId",
        "messageId",
        "sentTime",
        "data"
    ]
}

=== nmsa/tma-framework-m/interface/atmosphere_tma-m_schema-examples/example_2.json
{
    "probeId": 679,
    "resourceId": 81,
    "messageId": 1002,
    "sentTime": 1524780030,
    "data": [
        {
            "type": "event",
            "descriptionId": 2018,
            "observations": [{
                    "time": 1524782445,
                    "value": -1
                }, 
                {
                    "time": 1524782410,
                    "value": -1
                }, 
                {
                    "time": 1524782411,
                    "value": -1
                }, 
                {
                    "time": 1524782412,
                    "value": -1
                }, 
                {
                    "time": 1524782413,
                    "value": -1
                }, 
                {
                    "time": 1524782414,
                    "value": -1
                }, 
                {
                    "time": 1524782415,
                    "value": -1
                }, 
                {
                    "time": 1524782416,
                    "value": -1
                }
            ]
        },
        {
            "type": "measurement",
            "descriptionId": 19,
            "observations": [
                {
                    "time": 925,
                    "value": 640.75
                },
                {
                    "time": 783,
                    "value": -6.25
                },
                {
                    "time": 666,
                    "value": 533.0
                },
                {
                    "time": 52,
                    "value": 337.0
                }
            ]
        },
        {
            "type": "measurement",
            "descriptionId": 768,
            "observations": [
                {
                    "time": 593,
                    "value": 691.75
                },
                {
                    "time": 838,
                    "value": 564.25
                },
                {
                    "time": 334,
                    "value": 209.0
                }
            ]
        },
        {
            "type": "measurement",
            "descriptionId": 747,
            "observations": [
                {
                    "time": 165,
                    "value": 497.5
                },
                {
                    "time": 535,
                    "value": 151.25
                },
                {
                    "time": 272,
                    "value": 442.25
                }
            ]
        },
        {
            "type": "measurement",
            "descriptionId": 349,
            "observations": [
                {
                    "time": 300,
                    "value": 982.75
                },
                {
                    "time": 817,
                    "value": 786.25
                }
            ]
        }
    ]
}
